import json
import os

SCENARIOS = {
  "easy": [{"id": "easy_001", "will_text": "Delete all my social media accounts. Transfer my photos and videos to my daughter Sarah. Cancel all subscriptions.", "beneficiaries": ["Sarah"], "executor": "Sarah", "assets": [{"id": "instagram", "platform": "Instagram", "category": "social", "has_monetary_value": False, "is_private": False, "has_active_subscription": False, "linked_to_other_assets": False}, {"id": "facebook", "platform": "Facebook", "category": "social", "has_monetary_value": False, "is_private": False, "has_active_subscription": False, "linked_to_other_assets": False}, {"id": "google_photos", "platform": "Google Photos", "category": "storage", "has_monetary_value": False, "is_private": True, "has_active_subscription": False, "linked_to_other_assets": True}, {"id": "spotify", "platform": "Spotify", "category": "subscription", "has_monetary_value": False, "is_private": False, "has_active_subscription": True, "linked_to_other_assets": False}, {"id": "netflix", "platform": "Netflix", "category": "subscription", "has_monetary_value": False, "is_private": False, "has_active_subscription": True, "linked_to_other_assets": False}], "gold_actions": {"instagram": "delete_permanently", "facebook": "delete_permanently", "google_photos": "transfer_to_beneficiary", "spotify": "cancel_subscription", "netflix": "cancel_subscription"}}],
  "medium": [{"id": "medium_001", "will_text": "Give my online stuff to my kids. They should have what's useful.", "beneficiaries": ["kid_1", "kid_2"], "executor": "kid_1", "assets": [{"id": "netflix", "platform": "Netflix", "category": "subscription", "has_monetary_value": False, "is_private": False, "has_active_subscription": True, "linked_to_other_assets": False}, {"id": "crypto_wallet", "platform": "Coinbase", "category": "financial", "has_monetary_value": True, "is_private": True, "has_active_subscription": False, "linked_to_other_assets": False}, {"id": "work_slack", "platform": "Slack (Work)", "category": "professional", "has_monetary_value": False, "is_private": True, "has_active_subscription": False, "linked_to_other_assets": False}, {"id": "journal_blog", "platform": "Personal Blog", "category": "personal", "has_monetary_value": False, "is_private": True, "has_active_subscription": False, "linked_to_other_assets": False}, {"id": "github", "platform": "GitHub", "category": "professional", "has_monetary_value": False, "is_private": False, "has_active_subscription": False, "linked_to_other_assets": False}, {"id": "google_drive", "platform": "Google Drive", "category": "storage", "has_monetary_value": False, "is_private": True, "has_active_subscription": False, "linked_to_other_assets": True}], "gold_actions": {"netflix": "transfer_to_beneficiary", "crypto_wallet": "transfer_to_beneficiary", "work_slack": "archive_and_hold", "journal_blog": "preserve_memorialize", "github": "transfer_to_beneficiary", "google_drive": "transfer_to_beneficiary"}}],
  "hard": [{"id": "hard_001", "will_text": "My daughter Priya gets everything digital. She is my heir.", "beneficiaries": ["Priya", "Rahul"], "executor": "Rahul", "conflict_note": "Son Rahul is listed as executor but daughter Priya is listed as heir. Business email is active with clients. Secret secondary email discovered.", "assets": [{"id": "primary_gmail", "platform": "Gmail (Personal)", "category": "personal", "has_monetary_value": False, "is_private": True, "has_active_subscription": False, "linked_to_other_assets": True}, {"id": "business_email", "platform": "Gmail (Business)", "category": "professional", "has_monetary_value": True, "is_private": False, "has_active_subscription": True, "linked_to_other_assets": True}, {"id": "secret_email", "platform": "ProtonMail (Unknown)", "category": "personal", "has_monetary_value": False, "is_private": True, "has_active_subscription": False, "linked_to_other_assets": False}, {"id": "crypto_portfolio", "platform": "Binance", "category": "financial", "has_monetary_value": True, "is_private": True, "has_active_subscription": False, "linked_to_other_assets": False}, {"id": "aws_account", "platform": "AWS (Business)", "category": "professional", "has_monetary_value": True, "is_private": False, "has_active_subscription": True, "linked_to_other_assets": True}, {"id": "icloud", "platform": "iCloud", "category": "storage", "has_monetary_value": False, "is_private": True, "has_active_subscription": True, "linked_to_other_assets": False}, {"id": "linkedin", "platform": "LinkedIn", "category": "professional", "has_monetary_value": False, "is_private": False, "has_active_subscription": False, "linked_to_other_assets": False}, {"id": "domain_registrar", "platform": "GoDaddy (Business Domain)", "category": "financial", "has_monetary_value": True, "is_private": False, "has_active_subscription": True, "linked_to_other_assets": True}], "gold_actions": {"primary_gmail": "transfer_to_beneficiary", "business_email": "flag_for_human_review", "secret_email": "flag_for_human_review", "crypto_portfolio": "transfer_to_beneficiary", "aws_account": "flag_for_human_review", "icloud": "transfer_to_beneficiary", "linkedin": "preserve_memorialize", "domain_registrar": "flag_for_human_review"}}]
}

def get_scenario(difficulty: str, index: int = 0):
    return SCENARIOS[difficulty][index]